branches:
  only:
  - master
language: node_js
node_js:
  - "14"
services: 
  - docker
before_install:
  - docker build -t ibrahimafarhan/voting-app-webapp .
deploy:
  provider: script
  script: sh docker-push.sh
  on:
    branch: master